---
- name: show version test
  hosts: all
  gather_facts: false
  connection: ansible.netcommon.network_cli

  tasks:
    - name: show version
      cisco.ios.ios_command:
        commands: show version
      register: output

